export const MODELS = [
  { id: 'nvidia/nemotron-mini-4b-instruct', provider: 'nvidia', label: 'Nemotron Mini 4B' },
  { id: 'nvidia/nemotron-3-nano-30b-a3b', provider: 'nvidia', label: 'Nemotron 3 Nano 30B' },
  { id: 'nvidia/nemotron-3-super-120b-a12b', provider: 'nvidia', label: 'Nemotron 3 Super 120B' },
  { id: 'meta/llama-3.1-8b-instruct', provider: 'nvidia', label: 'Llama 3.1 8B' },
  { id: 'meta/llama-3.2-3b-instruct', provider: 'nvidia', label: 'Llama 3.2 3B' },
  { id: 'mistralai/mistral-small-4-119b-2603', provider: 'nvidia', label: 'Mistral Small 4' },
  { id: 'mistralai/mistral-nemotron', provider: 'nvidia', label: 'Mistral Nemotron' },
  { id: 'mistralai/mixtral-8x7b-instruct-v0.1', provider: 'nvidia', label: 'Mixtral 8x7B' },
  { id: 'qwen/qwen3-next-80b-a3b-instruct', provider: 'nvidia', label: 'Qwen 3 Next 80B' },
  { id: 'google/gemma-2-2b-it', provider: 'nvidia', label: 'Gemma 2 2B' },
  { id: 'google/gemma-3n-e2b-it', provider: 'nvidia', label: 'Gemma 3N E2B' },
  { id: 'upstage/solar-10.7b-instruct', provider: 'nvidia', label: 'Solar 10.7B' },
  { id: 'minimaxai/minimax-m3', provider: 'nvidia', label: 'MiniMax M3' },
];
