export const MODELS = [
  { id: 'deepseek-ai/deepseek-v4-flash', provider: 'nvidia', label: 'DeepSeek V4 Flash' },
  { id: 'deepseek-ai/deepseek-v4-pro', provider: 'nvidia', label: 'DeepSeek V4 Pro' },
  { id: 'meta/llama-3.3-70b-instruct', provider: 'nvidia', label: 'Llama 3.3 70B' },
  { id: 'meta/llama-3.1-8b-instruct', provider: 'nvidia', label: 'Llama 3.1 8B' },
  { id: 'meta/llama-3.1-70b-instruct', provider: 'nvidia', label: 'Llama 3.1 70B' },
  { id: 'meta/llama-4-maverick-17b-128e-instruct', provider: 'nvidia', label: 'Llama 4 Maverick 17B' },
  { id: 'meta/llama-3.2-3b-instruct', provider: 'nvidia', label: 'Llama 3.2 3B' },
  { id: 'meta/llama-3.2-1b-instruct', provider: 'nvidia', label: 'Llama 3.2 1B' },
  { id: 'mistralai/mistral-large', provider: 'nvidia', label: 'Mistral Large' },
  { id: 'mistralai/mistral-small-4-119b-2603', provider: 'nvidia', label: 'Mistral Small 4' },
  { id: 'mistralai/ministral-14b-instruct-2512', provider: 'nvidia', label: 'Ministral 14B' },
  { id: 'mistralai/mixtral-8x22b-v0.1', provider: 'nvidia', label: 'Mixtral 8x22B' },
  { id: 'mistralai/mixtral-8x7b-instruct-v0.1', provider: 'nvidia', label: 'Mixtral 8x7B' },
  { id: 'google/gemma-3-12b-it', provider: 'nvidia', label: 'Gemma 3 12B' },
  { id: 'google/gemma-3-4b-it', provider: 'nvidia', label: 'Gemma 3 4B' },
  { id: 'google/gemma-4-31b-it', provider: 'nvidia', label: 'Gemma 4 31B' },
  { id: 'qwen/qwen3.5-397b-a17b', provider: 'nvidia', label: 'Qwen 3.5 397B' },
  { id: 'qwen/qwen3-next-80b-a3b-instruct', provider: 'nvidia', label: 'Qwen 3 Next 80B' },
  { id: 'microsoft/phi-3.5-moe-instruct', provider: 'nvidia', label: 'Phi-3.5 MoE' },
  { id: 'ai21labs/jamba-1.5-large-instruct', provider: 'nvidia', label: 'AI21 Jamba 1.5 Large' },
  { id: 'minimaxai/minimax-m3', provider: 'nvidia', label: 'MiniMax M3' },
  { id: 'moonshotai/kimi-k2.6', provider: 'nvidia', label: 'Moonshot Kimi K2.6' },
  { id: 'z-ai/glm-5.2', provider: 'nvidia', label: 'GLM 5.2' },
  { id: 'bytedance/seed-oss-36b-instruct', provider: 'nvidia', label: 'ByteDance Seed 36B' },
  { id: '01-ai/yi-large', provider: 'nvidia', label: 'Yi Large' },
  { id: 'nvidia/llama-3.1-nemotron-70b-instruct', provider: 'nvidia', label: 'Nemotron 70B' },
  { id: 'nvidia/nemotron-4-340b-instruct', provider: 'nvidia', label: 'Nemotron 4 340B' },
  { id: 'databricks/dbrx-instruct', provider: 'nvidia', label: 'DBRX Instruct' },
];
